// ecommerce-v/src/views/Products.vue
<template>
  <div class="container">
    <div class="row py-5">
      <div class="col-4" v-for="(product, index) in products" :key="index">
        <div class="card">
          <img :src="require('@/assets/img/' + product.img)" alt="..." />
          <div class="card-body">
            <h5 class="card-title">{{ product.name }} - {{ product.price }}</h5>
            <p class="card-text">{{ product.description }}</p>
            <a class="btn btn-primary" v-on:click="changeView(index)"
              >Ver detalles</a
            >
          </div>
        </div>
      </div>
    </div>
  </div>
</template>

<script lang="ts">
import productService from "../services/productService.js";
const products = productService.products;
console.log(products[0].img);
export default {
  data() {
    return {
      products,
    };
  },
  name: "Home",
  components: {},
  methods: {
    changeView: function (id) {
      this.$router.push({ name: "newLocation", params: { id: id } });
    },
  },
};
</script>

// ecommerce-r/src/components/products/products.jsx
import "./Products.css";
import productService from "../../services/productService";
import { Link } from "react-router-dom";
function Products() {
  return (
    <div className="container">
      <div className="row py-5">
        {productService.products.map((product, index) => {
          return (
            <div className="col-4">
              <div className="card">
                <img src={product.img} alt="product" />
                <div className="card-body">
                  <h5 className="card-title">
                    {product.name} - {product.price}
                  </h5>
                  <p className="card-text">{product.description}</p>
                  <Link to={`/product/${index}`}>
                    <a className="btn btn-primary">Ver detalles</a>
                  </Link>
                </div>
              </div>
            </div>
          );
        })}
        ;
      </div>
    </div>
  );
}

export default Products;
